spring:
  liquibase:
    change-log: classpath:liquibase-changeLog.xml
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/shop
    platform: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      database-platform;: PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true



