spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/shop
    platform: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      database-platform;: PostgreSQLDialect

